# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mistocr',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/mistocr',
                'lib_path': 'mistocr'},
  'syms': {'mistocr.core': {'mistocr.core.foo': ('core.html#foo', 'mistocr/core.py')}}}
