"""OCR for PDFs using Mistral API"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['logger', 'ocr_model', 'ocr_endpoint', 'get_api_key', 'run_single', 'upload_pdf', 'create_batch_entry',
           'prep_pdf_batch', 'submit_batch', 'wait_for_job', 'download_results', 'prep_batch', 'run_batch',
           'single_to_batch_result', 'save_images', 'save_page', 'save_pages', 'get_paths', 'ocr_pdf', 'read_pgs',
           'subset_pdf']

# %% ../nbs/00_core.ipynb #044c5702
from fastcore.all import *
import os, re, json, time, base64, tempfile, logging
from io import BytesIO
from pathlib import Path
from PIL import Image
from mistralai import Mistral
import PyPDF2
import logging

# %% ../nbs/00_core.ipynb #46c2ca53
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.WARNING, format='%(name)s - %(levelname)s - %(message)s')
logger.setLevel(logging.DEBUG)

# %% ../nbs/00_core.ipynb #e0cbb18d
def get_api_key(
    key:str=None # Mistral API key
    ):
    "Get Mistral API key from parameter or environment"
    key = key or os.getenv("MISTRAL_API_KEY")
    if not key: raise ValueError("MISTRAL_API_KEY not found")
    return key

# %% ../nbs/00_core.ipynb #b0bdceb2
ocr_model = "mistral-ocr-latest"
ocr_endpoint = "/v1/ocr"

# %% ../nbs/00_core.ipynb #8d3b35e0
def run_single(
    path,                   # Path to PDF
    inc_img=True,           # Include image in response
    extract_header=True,    # Extract header
    extract_footer=True,    # Extract footer
    key=None                # Mistral API key
    ) -> 'OCRResponse':     # OCR response 
    "Run direct OCR on a single PDF (no batch queue)"
    path = Path(path)
    b64 = base64.b64encode(path.read_bytes()).decode('utf-8')
    c = Mistral(api_key=get_api_key(key))
    return c.ocr.process(
        model=ocr_model, 
        document=dict(type="document_url", document_url=f"data:application/pdf;base64,{b64}"), 
        include_image_base64=inc_img,
        extract_header=extract_header, 
        extract_footer=extract_footer)

# %% ../nbs/00_core.ipynb #61b07099
def upload_pdf(
    path:str, # Path to PDF file
    key:str=None # Mistral API key
    ) -> tuple[str, Mistral]: # Mistral pdf signed url and client
    "Upload PDF to Mistral and return signed URL"
    c = Mistral(api_key=get_api_key(key))
    path = Path(path)
    uploaded = c.files.upload(file=dict(file_name=path.stem, content=path.read_bytes()), purpose="ocr")
    return c.files.get_signed_url(file_id=uploaded.id).url, c

# %% ../nbs/00_core.ipynb #9e74ef55
def create_batch_entry(
    path:str, # Path to PDF file, 
    url:str, # Mistral signed URL
    cid:str=None, # Custom ID (by default using the file name without extension)
    inc_img:bool=True, # Include image in response
    extract_header:bool=True, # Extract headers from document
    extract_footer:bool=True # Extract footers from document
    ) -> dict[str, str | dict[str, str | bool]]: # Batch entry dict
    "Create a batch entry dict for OCR"
    path = Path(path)
    if not cid: cid = path.stem
    return dict(
        custom_id=cid, 
        body=dict(
            document=dict(
                type="document_url", 
                document_url=url), 
                include_image_base64=inc_img, 
                extract_header=extract_header, 
                extract_footer=extract_footer
            )
        )

# %% ../nbs/00_core.ipynb #cd0c3c2a
def prep_pdf_batch(
    path:str, # Path to PDF file, 
    cid:str=None, # Custom ID (by default using the file name without extention)
    inc_img:bool=True, # Include image in response
    key=None # API key
    ) -> dict: # Batch entry dict
    "Upload PDF and create batch entry in one step"
    url, c = upload_pdf(path, key)
    return create_batch_entry(path, url, cid, inc_img), c

# %% ../nbs/00_core.ipynb #376dfcfc
def submit_batch(
    entries:list[dict], # List of batch entries, 
    c:Mistral=None, # Mistral client, 
    model:str=ocr_model, # Model name, 
    endpoint:str=ocr_endpoint # Endpoint name
    ) -> dict: # Job dict
    "Submit batch entries and return job"
    with tempfile.NamedTemporaryFile(mode='w', suffix='.jsonl', delete=True) as f:
        for e in entries: f.write(json.dumps(e) + '\n')
        f.flush()
        batch_data = c.files.upload(file=dict(file_name="batch.jsonl", content=open(f.name, "rb")), purpose="batch")
    return c.batch.jobs.create(input_files=[batch_data.id], model=model, endpoint=endpoint)

# %% ../nbs/00_core.ipynb #a5f0cd6a
def wait_for_job(
    job, # Batch job from submit_batch
    c=None, # Mistral client
    poll_interval=10, # Seconds between status checks
    timeout=None # Max total seconds before timeout
    ) -> dict: # Job dict
    "Poll job until completion, printing only on status change"
    prev_status, elapsed = None, 0
    while job.status in ["QUEUED", "RUNNING"]:
        total, done = job.total_requests or 0, (job.succeeded_requests or 0) + (job.failed_requests or 0)
        curr_status = f"{job.status} ({done}/{total})" if total > 1 else job.status
        if curr_status != prev_status: print(f"Job {job.id}: {curr_status} ({elapsed}s)")
        prev_status = curr_status
        if timeout and elapsed >= timeout:
            c.batch.jobs.cancel(job_id=job.id)
            raise TimeoutError(f"Job {job.id} timed out after {elapsed}s and was cancelled")
        time.sleep(poll_interval)
        elapsed += poll_interval
        job = c.batch.jobs.get(job_id=job.id)
    print(f"Job {job.id}: {job.status} ({elapsed}s)")
    return job


# %% ../nbs/00_core.ipynb #462a85f1
def download_results(
    job:dict, # Job dict, 
    c:Mistral=None # Mistral client
    ) -> list[dict]: # List of results
    "Download and parse batch job results"
    content = c.files.download(file_id=job.output_file).read().decode('utf-8')
    return [json.loads(line) for line in content.strip().split('\n') if line]

# %% ../nbs/00_core.ipynb #79c9ef5d
def prep_batch(
    pdfs:list[Path],    # List of PDF paths
    inc_img:bool=True,  # Include images in response
    key:str=None        # Mistral API key
    ) -> tuple[list[dict], Mistral]: # Batch entries and Mistral client
    "Upload PDFs and prepare batch entries"
    entries, c = [], None
    for pdf in pdfs:
        entry, c = prep_pdf_batch(pdf, inc_img=inc_img, key=key)
        entries.append(entry)
    return entries, c

# %% ../nbs/00_core.ipynb #63e8dc2c
def run_batch(
    entries:list[dict],   # Batch entries from prep_batch
    c:Mistral,            # Mistral client
    poll_interval:int=2   # Seconds between status checks
    ) -> list[dict]:      # List of OCR results
    "Submit batch, wait for completion, and download results"
    job = submit_batch(entries, c)
    job = wait_for_job(job, c, poll_interval)
    if job.status != 'SUCCESS': raise Exception(f"Job failed with status: {job.status}")
    return download_results(job, c)

# %% ../nbs/00_core.ipynb #5bbbc8c0
def single_to_batch_result(
    resp,      # OCRResponse from run_single
    cid        # Custom ID (typically PDF filename stem)
    ) -> list: # List containing single batch-format result
    "Adapt single OCR response to batch result format for uniform downstream processing"
    pages = [dict(index=p.index, markdown=p.markdown, images=[dict(id=img.id, image_base64=img.image_base64) for img in (p.images or [])]) for p in resp.pages]
    return [dict(custom_id=cid, response=dict(body=dict(pages=pages)))]

# %% ../nbs/00_core.ipynb #bf4c6dd5
def save_images(
    page:dict, # Page dict
    img_dir:str='img' # Directory to save images
    ) -> None:
    "Save all images from a page to directory"
    for img in page.get('images', []):
        if img.get('image_base64') and img.get('id'):
            img_bytes = base64.b64decode(img['image_base64'].split(',')[1])
            Image.open(BytesIO(img_bytes)).save(img_dir / img['id'])

# %% ../nbs/00_core.ipynb #a6e5dfdc
def save_page(
    page:dict, # Page dict, 
    dst:str, # Directory to save page
    img_dir:str='img' # Directory to save images
    ) -> None:
    "Save single page markdown and images"
    (dst / f"page_{page['index']+1}.md").write_text(page['markdown'])
    if page.get('images'):
        img_dir.mkdir(exist_ok=True)
        save_images(page, img_dir)

# %% ../nbs/00_core.ipynb #5feac02b
def save_pages(
    ocr_resp:dict, # OCR response, 
    dst:str, # Directory to save pages, 
    cid:str # Custom ID
    ) -> Path: # Output directory
    "Save markdown pages and images from OCR response to output directory"
    dst = Path(dst) / cid
    dst.mkdir(parents=True, exist_ok=True)
    img_dir = dst / 'img'
    for page in ocr_resp['pages']: save_page(page, dst, img_dir)
    return dst

# %% ../nbs/00_core.ipynb #74fef784
def get_paths(
    path:str # Path to file or folder
    ) -> list[Path]: # List of PDF paths
    "Get list of PDFs from file or folder"
    path = Path(path)
    if path.is_file(): return [path]
    if path.is_dir():
        pdfs = path.ls(file_exts='.pdf')
        if not pdfs: raise ValueError(f"No PDFs found in {path}")
        return pdfs
    raise ValueError(f"Path not found: {path}")

# %% ../nbs/00_core.ipynb #b1499a0e
def ocr_pdf(
    path:str,           # Path to PDF file or folder,
    dst:str='md',       # Directory to save markdown pages, 
    inc_img:bool=True,  # Include image in response, 
    key:str=None,       # API key, 
    poll_interval:int=2 # Poll interval in seconds
    ) -> list[Path]:    # List of output directories
    "OCR PDF(s) and save results. Single PDF uses direct mode; multiple uses batch"
    pdfs = get_paths(path)
    if len(pdfs) == 1: results = single_to_batch_result(run_single(pdfs[0], inc_img, key=key), pdfs[0].stem)
    else:
        entries, c = prep_batch(pdfs, inc_img, key)
        results = run_batch(entries, c, poll_interval)
    res = L([save_pages(r['response']['body'], dst, r['custom_id']) for r in results])
    return res[0] if len(res) == 1 else res

# %% ../nbs/00_core.ipynb #dcdbdf1f
def read_pgs(
    path:str, # OCR output directory, 
    join:bool=True # Join pages into single string
    ) -> str|list[str]: # Joined string or list of page contents
    "Read specific page or all pages from OCR output directory"
    path = Path(path)
    pgs = sorted(path.glob('page_*.md'), key=lambda p: int(p.stem.split('_')[1]))
    contents = L([p.read_text() for p in pgs])
    return '\n\n'.join(contents) if join else contents

# %% ../nbs/00_core.ipynb #9d14fcfc
def subset_pdf(
    path:str, # Path to PDF file
    start:int=1, # Start page (1-based)
    end:int=None, # End page (1-based, inclusive)
    dst:str='.' # Output directory
    ) -> Path: # Path to subset PDF
    "Extract page range from PDF and save with range suffix"
    path = Path(path)
    writer = PyPDF2.PdfWriter()
    with open(path, 'rb') as f:
        reader = PyPDF2.PdfReader(f)
        n = len(reader.pages)
        end = end or n
        s, e = max(0, start-1), min(n, end) - 1
        for i in range(s, e+1): writer.add_page(reader.pages[i])
    suffix = f"_p{s+1}-{e+1}" if s>0 or e<n-1 else ""
    out = Path(dst) / f"{path.stem}{suffix}.pdf"
    with open(out, 'wb') as f: writer.write(f)
    return out
