"""Run OCR + fix the markdown headings + describe images/figures for a single pdf file"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_pipeline.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_pipeline.ipynb 2
from fastcore.all import *
from .core import read_pgs, ocr_pdf
from .refine import add_img_descs, fix_hdgs
from pathlib import Path
from asyncio import Semaphore, gather, sleep
import os, json, shutil
