"""End-to-End Pipeline: PDF OCR, Markdown Heading Correction, and AI Image Descriptions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_pipeline.ipynb.

# %% auto 0
__all__ = ['logger', 'pdf_to_md']

# %% ../nbs/02_pipeline.ipynb 3
from fastcore.all import *
from .core import read_pgs, ocr_pdf
from .refine import add_img_descs, fix_hdgs
from pathlib import Path
from asyncio import Semaphore, gather, sleep
import tempfile
import os, json, shutil
import logging

# %% ../nbs/02_pipeline.ipynb 5
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.WARNING, format='%(name)s - %(levelname)s - %(message)s')
logger.setLevel(logging.INFO)

# %% ../nbs/02_pipeline.ipynb 6
async def pdf_to_md(
    pdf_path:str,                   # Path to input PDF file
    dst:str,                        # Destination directory for output markdown
    ocr_dst:str=None,               # Optional OCR output directory
    model:str='claude-sonnet-4-5',  # Model to use for heading fixes and image descriptions
    add_img_desc:bool=True,         # Whether to add image descriptions
    progress:bool=True,             # Whether to show progress messages
    fix_kwargs:dict=None,           # Extra kwargs for fix_hdgs (e.g. prompt, max_tokens)
    desc_kwargs:dict=None,          # Extra kwargs for add_img_descs (e.g. prompt, batch_sz, max_conc)
    ):
    "Convert a single PDF to markdown with OCR, fixed heading hierarchy, and optional image descriptions. Batch version planned. See `fix_hdgs` and `add_img_descs` for available kwargs."
    if isinstance(pdf_path, (list, tuple)): raise ValueError("pdf_to_md processes a single PDF; batch version coming soon")
    fix_kwargs,desc_kwargs = fix_kwargs or {}, desc_kwargs or {}
    # Unless a specific model is specified for the headings fix or img description is pass through their respective kwargs, we use the model param.
    fix_kwargs.setdefault('model', model)
    desc_kwargs.setdefault('model', model)
    cleanup = ocr_dst is None
    if cleanup: ocr_dst = tempfile.mkdtemp()
    n_steps = 3 if add_img_desc else 2
    if progress: logger.info(f"Step 1/{n_steps}: Running OCR on {pdf_path}...")
    ocr_dir = ocr_pdf(pdf_path, ocr_dst)
    if progress: logger.info(f"Step 2/{n_steps}: Fixing heading hierarchy...")
    fix_hdgs(ocr_dir, model=model, **fix_kwargs)
    if add_img_desc:
        if progress: logger.info(f"Step 3/{n_steps}: Adding image descriptions...")
        await add_img_descs(ocr_dir, dst=dst, model=model, progress=progress, **desc_kwargs)
    elif dst != str(ocr_dir): shutil.copytree(ocr_dir, dst, dirs_exist_ok=True)
    if cleanup: shutil.rmtree(ocr_dst)
    if progress: logger.info("Done!")


