"""End-to-End Pipeline: PDF OCR, Markdown Heading Correction, and AI Image Descriptions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_pipeline.ipynb.

# %% auto 0
__all__ = ['pdf_to_md']

# %% ../nbs/02_pipeline.ipynb 3
from fastcore.all import *
from .core import read_pgs, ocr_pdf
from .refine import add_img_descs, fix_hdgs
from pathlib import Path
from asyncio import Semaphore, gather, sleep
import os, json, shutil

# %% ../nbs/02_pipeline.ipynb 4
@delegates(add_img_descs)
async def pdf_to_md(
    pdf_path:str, # Path to input PDF file
    dst:str, # Destination directory for output markdown
    ocr_output:str=None, # Optional OCR output directory (defaults to pdf_path stem)
    model:str='claude-sonnet-4-5', # Model to use for heading fixes and image descriptions
    add_img_desc:bool=True, # Whether to add image descriptions
    progress:bool=True, # Whether to show progress messages
    **kwargs):
    "Convert PDF to markdown with OCR, fixed heading hierarchy, and optional image descriptions"
    n_steps = 3 if add_img_desc else 2
    if progress: print(f"Step 1/{n_steps}: Running OCR on {pdf_path}...")
    ocr_dirs = ocr_pdf(pdf_path, ocr_output or 'ocr_temp')
    ocr_dir = ocr_dirs[0]
    if progress: print(f"Step 2/{n_steps}: Fixing heading hierarchy...")
    fix_hdgs(ocr_dir, model=model)
    if add_img_desc:
        if progress: print(f"Step 3/{n_steps}: Adding image descriptions...")
        await add_img_descs(ocr_dir, dst=dst, model=model, progress=progress, **kwargs)
    elif dst and Path(dst) != ocr_dir: shutil.copytree(ocr_dir, dst, dirs_exist_ok=True)
    if progress: print("Done!")
