"""Postprocessing markdown files including fixing heading hierarchy and adding image descriptions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_refine.ipynb.

# %% auto 0
__all__ = ['get_hdgs']

# %% ../nbs/01_refine.ipynb 11
def get_hdgs(
    md:str # Markdown file string
    ):
    "Return the markdown headings"
    # Sanitize removing '#' in python snippet if any
    md = sub(r'```[\s\S]*?```', '', md)
    return findall(r'^#{1,6} .+$', md, MULTILINE)


